[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
domius-core = { path = "../../domius-core", features = ["wasm"] }
domius-web = { path = "../../domius-web" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Window", "Document", "Element", "Node", "HtmlElement",
    "HtmlButtonElement", "HtmlInputElement", "MouseEvent", "Event",
    "console",
] }
